openapi: 3.0.1
info:
  title: '@jupiterone/graph-rumble'
  description: graph-rumble integration project
  x-cortex-git:
    github:
      repository: JupiterOne/graph-rumble
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-rumble'
